apiVersion: v1
kind: Pod
metadata:
  name: altus-pod
  annotations:
    networking.gke.io/default-interface: 'eth1'
    networking.gke.io/interfaces: '[{"interfaceName":"eth1","interface":"altus-interface"},{"interfaceName":"eth0","network":"pod-network"}]'
    networking.gke.io/enable-multicast: "true"
spec:
  hostNetwork: false
  containers:
  - name: altus
    image: quay.io/telosalliance/altus
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    resources:
      requests:
        cpu: 400m
        memory: 8Gi
      limits:
        cpu: 400m
        memory: 8Gi
    ports:
    - containerPort: 21
      protocol: TCP
    - containerPort: 23
      protocol: TCP  
    - containerPort: 53
      protocol: TCP
    - containerPort: 53
      protocol: UDP
    - containerPort: 80
      protocol: TCP
    - containerPort: 139
      protocol: TCP
    - containerPort: 443
      protocol: TCP
    - containerPort: 445
      protocol: TCP
    - containerPort: 2015
      protocol: TCP
    - containerPort: 3389
      protocol: TCP
    - containerPort: 7000
      protocol: TCP
    - containerPort: 7800
      protocol: TCP
    - containerPort: 7801
      protocol: TCP
    - containerPort: 7802
      protocol: TCP
    - containerPort: 8443
      protocol: TCP
    - containerPort: 9999
      protocol: TCP
    - containerPort: 10011
      protocol: TCP
    - containerPort: 10516
      protocol: TCP
    - containerPort: 12001
      protocol: TCP
    - containerPort: 13087
      protocol: TCP
    - containerPort: 13090
      protocol: TCP
    - containerPort: 17472
      protocol: TCP
    - containerPort: 17475
      protocol: TCP
    - containerPort: 17724
      protocol: TCP
  imagePullSecrets:
    - name: quay-pull-secret