apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: pathfinder-vm
spec:
  size: 100Gi
  storageClassName: k8sfs
  source:
    http:
      url: https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: pathfinder
spec:
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [172.16.0.7/24]
  disks:
    - boot: true
      virtualMachineDiskName: pathfinder-vm
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: phones-vm
spec:
  size: 100Gi
  storageClassName: k8sfs
  source:
    http:
      url: https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: phones-vx
spec:
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [172.16.0.8/24]
  disks:
    - boot: true
      virtualMachineDiskName: pathfinder-vm