apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: radio-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [172.16.0.14/24]
  disks:
    - boot: true
      virtualMachineDiskName: radio-vm
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: content-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [172.16.0.15/24]
  disks:
    - boot: true
      virtualMachineDiskName: content-vm
---