
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: altus-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [172.16.0.10/24]
  disks:
    - boot: true
      virtualMachineDiskName: altus-linux-boot-dv
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: forza-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [172.16.0.11/24]
  disks:
    - boot: true
      virtualMachineDiskName: forza-linux-boot-dv
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: pdm-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [172.16.0.12/24]
  disks:
    - boot: true
      virtualMachineDiskName: pdm-linux-boot-dv
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: zephyr-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [172.16.0.13/24]
  disks:
    - boot: true
      virtualMachineDiskName: zephyr-linux-boot-dv