apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: altus-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [192.168.41.23/24]
  disks:
    - boot: true
      virtualMachineDiskName: altus-linux
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: forza-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [192.168.41.24/24]
  disks:
    - boot: true
      virtualMachineDiskName: linux-clone
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: pdm-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [192.168.41.25/24]
  disks:
    - boot: true
      virtualMachineDiskName: pdm-linux
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: zephyr-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [192.168.41.26/24]
  disks:
    - boot: true
      virtualMachineDiskName: zephyr-linux
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: radio-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [192.168.41.27/24]
  disks:
    - boot: true
      virtualMachineDiskName: radio-linux
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: content-linux
spec:
  autoRestartOnConfigurationChange: true
  osType: Linux
  compute:
    cpu:
      vcpus: 2
    memory:
      capacity: 8Gi
  interfaces:
    - name: eth0
      networkName: pod-network
      default: true
    - name: net1
      networkName: livewire
      ipAddresses: [192.168.41.28/24]
  disks:
    - boot: true
      virtualMachineDiskName: content-linux
---
