apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: altus-linux-snapshot
spec:
  volumeSnapshotClassName: csi-snapshot-class  # Use your snapshot class name
  source:
    persistentVolumeClaimName: altus-linux  # Your existing PVC name
