apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-traffic
  namespace: default  # Apply to default namespace, repeat for others if needed
spec:
  podSelector: {}    # Empty selector matches all pods
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}              # Empty rule allows all ingress traffic
  egress:
  - {}        