apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8sfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.21.237.31
  share: /var/nfs/k8sfs
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1