apiVersion: v1
kind: Service
metadata:
  name: pathfinder-service
spec:
  selector:
    kubevirt/vm: pathfinder
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: comms
    protocol: TCP
    port: 8000
  - name: comm2
    protocol: TCP
    port: 8001
  - name: comm3
    protocol: TCP
    port: 8002
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false