apiVersion: v1
kind: Service
metadata:
  name: wors-1-service
spec:
  selector:
    kubevirt/vm: windows-vm-1
  ports:
    - port: 21
      targetPort: 21
      name: ftp
      protocol: TCP
    - port: 23
      targetPort: 23
      name: telnet
      protocol: TCP
    - port: 53
      targetPort: 53
      name: dns-tcp
      protocol: TCP
    - port: 53
      targetPort: 53
      name: dns-udp
      protocol: UDP
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
    - port: 139
      targetPort: 139
      name: netbios
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP
    - port: 445
      targetPort: 445
      name: smb
      protocol: TCP
    - port: 2015
      targetPort: 2015
      name: db
      protocol: TCP
    - port: 3389
      targetPort: 3389
      name: rdp
      protocol: TCP
    - port: 7800
      targetPort: 7800
      name: custom-1
      protocol: TCP
    - port: 7802
      targetPort: 7802
      name: custom-2
      protocol: TCP
    - port: 8443
      targetPort: 8443
      name: https-alt
      protocol: TCP
    - port: 10011
      targetPort: 10011
      name: teamspeak
      protocol: TCP
    - port: 10516
      targetPort: 10516
      name: mgmt
      protocol: TCP
    - port: 12001
      targetPort: 12001
      name: stream
      protocol: TCP
    - port: 13087
      targetPort: 13087
      name: custom-3
      protocol: TCP
    - port: 13090
      targetPort: 13090
      name: custom-4
      protocol: TCP
    - port: 17472
      targetPort: 17472
      name: custom-5
      protocol: TCP
    - port: 17475
      targetPort: 17475
      name: custom-6
      protocol: TCP
    - port: 17724
      targetPort: 17724
      name: custom-7
      protocol: TCP
    - port: 9999
      targetPort: 9999
      name: custom-8
    - port: 7000
      targetPort: 7000
      name: custom-9
    - port: 7801
      targetPort: 7801
      name: custom-10
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false